version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mitienda
      DB_USERNAME: root
      DB_PASSWORD:

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mitienda
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
